title: Meteor Blaze Tutorial
subtitle: Blaze Tutorial
versions:
  - '1'
versioned-netlify-redirects:
  netlify_site_id: meteor-blaze-tutorial

logo:
  title:
  subtitle: Blaze Tutorial

sidebar_categories:
  null:
    - index
    - changelog
  Simple Todos:
    - simple-todos/index
    - simple-todos/01-creating-app
    - simple-todos/02-collections
    - simple-todos/03-forms-and-events
    - simple-todos/04-update-and-remove
    - simple-todos/05-styles
    - simple-todos/06-filter-tasks
    - simple-todos/07-adding-user-accounts
    - simple-todos/08-methods
    - simple-todos/09-publications
    - simple-todos/10-running-on-mobile
    - simple-todos/11-testing
    - simple-todos/12-deploying
    - simple-todos/13-next-steps
github_repo: 'meteor/blaze-tutorial'

url: http://blaze-tutorial.meteor.com/
root: /

source_dir: tutorial
content_root: tutorial

highlight:
  enable: false
